// web/pages/login.vue
<script setup lang="ts">
import { ref } from "vue";
import TextInput from "~/components/inputs/text-input.vue";
import ActionButton from "~/components/action-button.vue";
import Axios from "axios"

const email = ref("");
const password = ref("");
const error = ref("")

const login = async () => {

  try {

    const response = await Axios.post('http://localhost:1337/api/auth/local', { identifier: email.value, password: password.value })
    console.log(response)
  } catch (err) {
    if (err?.response?.data?.error?.name === 'ValidationError') {
      error.value = "Falsche Email-Adresse oder Passwort"
    }
  }

};
</script>

<template>
  <div class="container mx-auto">
    <h1 class="text-2xl font-bold text-blue-800">Stammtisch Login</h1>

    <div class="flex flex-col">
      <label for="email">Email</label>
      <text-input name="email" v-model="email" />
    </div>
    <div class="flex flex-col">
      <label for="password">Passwort</label>
      <text-input type="password" name="password" v-model="password" />
    </div>
    <action-button @click="login">Login</action-button>

    <div v-if="error" class="mt-5 p-3 bg-red-200 border-solid border border-red-400 rounded">
      {{ error }}
    </div>
  </div>
</template>

// web/pages/login/index.tsx
import type { NextPage } from "next";
import React, { useState } from "react";

import axios from "axios";

const Login: NextPage = () => {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const handleEmailChange = (e: React.MouseEvent<HTMLInputElement>) => {
    setEmail((e.target as HTMLInputElement).value);
  };
  const handlePasswordChange = (e: React.MouseEvent<HTMLInputElement>) => {
    setPassword((e.target as HTMLInputElement).value);
  };
  const loginUser = () => {
    console.log(email, password);
    axios
      .post(
        "http://localhost:1337/api/auth/local",
        {
          identifier: email,
          password: password,
        },
      )
      .then((response) => {
        console.log("User profile", response.data.user);
        console.log("User token", response.data.jwt);
      })
      .catch((error) => {
        console.log("An error occurred:", error.response);
      });
  };

  return (
    <main className="container mx-auto h-full flex flex-col justify-center p-3">
      <div>
        <h1 className="text-2xl font-bold">Stammtisch</h1>
        <input
          type="text"
          className="block px-2 py-1 bg-gray-200 rounded-lg text-lg focus:outline-none"
          placeholder="Email Adresse"
          onClick={handleEmailChange}
        />
        <input
          type="password"
          className="block px-2 py-1 bg-gray-200 rounded-lg text-lg focus:outline-none"
          placeholder="Passwort"
          onClick={handlePasswordChange}
        />
        <button onClick={loginUser}>Login</button>
      </div>
    </main>
  );
};

export default Login;
